### ISSUE TITLE
Global number must start with "+"

### ISSUE THREAD

**Issue by Inkal31899** [mangstadt/ez-vcard#152]
Fatal Exception: java.lang.IllegalStateException: [Error 26] Global number must start with "+".
       at ezvcard.parameter.VCardParameters$VCardParameterList._exception(VCardParameters.java:1741)
       at ezvcard.parameter.VCardParameters$VCardParameterList.asObject(VCardParameters.java:1713)
       at ezvcard.parameter.VCardParameters$VCardParameterList.get(VCardParameters.java:1694)
       at java.util.AbstractList$Itr.next(AbstractList.java:358)
       at java.util.AbstractCollection.toString(AbstractCollection.java:461)
       at java.lang.String.valueOf(String.java:2924)
       at java.lang.StringBuilder.append(StringBuilder.java:132) 

I am encountering a crash while parsing a VCF file using the ez-vcard library. Is there a way to prevent this crash? Any guidance or fixes would be appreciated.

**Comment by mangstadt** [comment]
Can you post the vCard file please?
